version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tyba_challenge_image
    container_name: tyba_challenge_service
    restart: always
    ports: 
      - 4001:4001
    environment:
      ENV: prod
    working_dir: /usr/src
    volumes:
      - ./:/usr/src